ARG VERSION=latest

FROM grafana/loki:${VERSION}

# Create the /etc/loki directory
RUN mkdir -p /etc/loki

# Copy the loki.yml configuration file to the container
COPY loki.yml /etc/loki/loki.yml

# Command to run Loki
CMD ["-config.file=/etc/loki/loki.yml"]